Updates openshift hooks and Gemfile updates.

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -4,15 +4,42 @@
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
 
-data="${OPENSHIFT_DATA_DIR}/assets"
-assets="${OPENSHIFT_REPO_DIR}/public"
+set -e
 
-# Remove the assets directory if it's empty
-cp -rf $assets/assets/* $OPENSHIFT_DATA_DIR
-find $assets/assets -maxdepth 0 -type d -empty -delete 2> /dev/null
-
-# Try to make the symlink
-ln -s -f $data $assets 2> /dev/null
-if [ $? -gt 0 ]; then
-  echo "Unable to create symlink to assets directory, using existing directory in repository"
+if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
+then
+    echo 1>&2
+    echo "Could not find mysql database.  Please run:" 1>&2
+    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+    echo 1>&2
 fi
+
+RETRY=60
+while [ $RETRY -gt 0 ] ; do
+    #reload env variables
+    for env_var in  $OPENSHIFT_HOMEDIR/.env/*
+    do
+        . $env_var
+    done
+
+    #check for db
+    if [ -n "$OPENSHIFT_MYSQL_DB_HOST" ]
+    then
+        echo "Database server found at $OPENSHIFT_MYSQL_DB_HOST. initializing..."
+        sleep 5
+        break
+    fi
+
+    sleep 1
+    RETRY=$(( $RETRY - 1 ))
+done
+
+if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
+then
+    exit 5
+fi
+
+pushd ${OPENSHIFT_REPO_DIR} > /dev/null
+bundle exec rake db:migrate RAILS_ENV="production"
+popd > /dev/null
