Updating action hook so that Jenkins build will re-create the symlink properly.

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -4,3 +4,14 @@
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
 
+data="${OPENSHIFT_DATA_DIR}/assets"
+assets="${OPENSHIFT_REPO_DIR}/public"
+
+# Remove the assets directory if it's empty
+find $assets/assets -maxdepth 0 -type d -empty -delete 2> /dev/null
+
+# Try to make the symlink
+ln -s -f $data $assets 2> /dev/null
+if [ $? -gt 0 ]; then
+  echo "Unable to create symlink to assets directory, using existing directory in repository"
+fi
